apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_ENDPOINT: $DB_ENDPOINT
  DB_PORT: $DB_PORT
  DB_NAME: $DB_NAME
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD